### ISSUE TITLE
Https_TLS_1_2 unit test failing (Mantis 2453)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#17]
org.opcfoundation.ua.common.ServiceResultException: Bad_CommunicationError (code=0x80050000, description="2147811328, peer not authenticated")
	at org.opcfoundation.ua.transport.https.HttpsClientPendingRequest.run(HttpsClientPendingRequest.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:397)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:827)
	at org.opcfoundation.ua.transport.https.HttpsClientPendingRequest.run(HttpsClientPendingRequest.java:130)
	... 3 more

NOTE:
Looks like there is a problem with the CipherSuite TLS_RSA_WITH_AES_256_CBC_SHA256, which does not work with the Java SSL classes for some reason. If we include TLS_RSA_WITH_AES_128_CBC_SHA or TLS_RSA_WITH_AES_256_CBC_SHA as an optional Cipher Suite, it works fine. I would recommend at this point, adding these as allowed TLS1.2 ciphers to the Profile specification.

**Comment by jouniaro** [comment]
There is nothing we can do about this, since the 256-bit CipherSuites are not implemented in the JCE. Instead the new TLS 1.2 PFS Profile (#61) includes a 128-bit CipherSuite that can be used, so that will be an option instead.
