### ISSUE TITLE
Decoding exceptions lead to Timeouts (Mantis 2430)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#19]
If Decoding exceptions occur on the client side, they will make the secure channel closed and leads eventually to a timeout, because the error is not returned properly to the client. 

The problem can be revealed with large strings, which overcome the MaxStringLength limit (64K by default).

A sample log:
03/21/2013 16:28:30.647 ERROR [TcpConnection/Read] org.opcfoundation.ua.transport.tcp.io.TcpConnection ? - localhost/127.0.0.1:6006 Error
org.opcfoundation.ua.encoding.DecodingException: Bad_EncodingLimitsExceeded (code=0x80080000, description="MaxStringLength 65535 < 227846")
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.assertStringLength(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getString(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getXmlElement(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getScalarObject(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getVariant(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getDataValue(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getDataValueArray(Unknown Source)
    at org.opcfoundation.ua.core.EncodeableSerializer$113.getEncodeable(Unknown Source)
    at org.opcfoundation.ua.encoding.utils.AbstractSerializer.getEncodeable(Unknown Source)
    at org.opcfoundation.ua.encoding.utils.SerializerComposition.getEncodeable(Unknown Source)
    at org.opcfoundation.ua.encoding.binary.BinaryDecoder.getMessage(Unknown Source)
    at org.opcfoundation.ua.transport.tcp.io.TcpConnection$ReadThread.run(Unknown Source)
03/21/2013 16:28:30.654 ERROR [TcpConnection/Read] org.opcfoundation.ua.transport.tcp.io.TcpConnection ? - localhost/127.0.0.1:6006 Error
org.opcfoundation.ua.common.ServiceResultException: Bad_SecureChannelIdInvalid (code=0x80220000, description="Bad_SecureChannelIdInvalid (code=0x80220000, description="The specified secure channel is not longer valid.")")
    at org.opcfoundation.ua.transport.tcp.io.TcpConnection$ReadThread.run(Unknown Source)
03/21/2013 16:28:31.660 ERROR [TcpConnection/Read] org.opcfoundation.ua.transport.tcp.io.TcpConnection ? - localhost/127.0.0.1:6006 Error
org.opcfoundation.ua.common.ServiceResultException: Bad_SecureChannelIdInvalid (code=0x80220000, description="Bad_SecureChannelIdInvalid (code=0x80220000, description="The specified secure channel is not longer valid.")")
    at org.opcfoundation.ua.transport.tcp.io.TcpConnection$ReadThread.run(Unknown Source)

**Comment by bjakke** [comment]
I'm not sure if this issue is valid anymore. Also I'm not sure if the issue means the problem is the timeout or channel closing on erroneus message. Anyway the current implementation either succeeds or fails completely. If a DecodingException catch is added to TcpConnection.ReadThread and we would treat it as a skip (with error logging), e.g.
```
IEncodeable message;
try{
	message = dec.getMessage();
}catch(DecodingException e){
	if (e.getCause()!=null && e.getCause() instanceof EOFException) {
		throw e;
	} else {
		logger.error("Cannot decode message, skipping", e);
		continue;
	}
}
```
Then the observed behaviour actually becomes more what this bug report reports as the problem, i.e. the messages will wait until timeouting. Probably some kind of partial decoding should be implemented in order to resolve this issue (i.e. decode requestheader separately so we know which message it is which is failing, otherwise we have no know of notifying it has failed). Moving to 1.03.342, however resolving might take longer as this requires architectural changes on how the stack decodes messages.
